version: '3.3'

services:
  web:
    env_file: ./.env
    environment:
       CS_VERSION: "1.1.4"
       TARGET_SYSTEM: ${TARGET_SYSTEM}
       TYPE_OF_INSTALLATION: ${TYPE_OF_INSTALLATION}
#    build:
#      context: ./build-docker/web/
    container_name: web
    image: "climatestation/web:2.0"
    depends_on:
      - postgres
      - hub
    networks:
      - default
    ports:
      - ${CS_WEBPORT}:8080
      - 6767:6767
    restart: unless-stopped
    volumes:
      - ./log/web:/var/log/uwsgi
      # - ./src:/var/www/climatestation:rw
      - ${DATA_VOLUME}:/data:rw
      - ${TMP_VOLUME}:/tmp/climatestation:rw

  hub:
    env_file: ./.env
#    build:
#      context: ./build-docker/jupyterhub/
    container_name: jupyterhub
    image: "climatestation/jupyterhub:latest"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      default:
      jupyterhub:
        aliases:
          - hub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw

  postgres:
    env_file: ./.env
    container_name: postgres
    environment:
      TARGET_SYSTEM: ${TARGET_SYSTEM}
      DB_VERSION: "114"
      PGPASSWORD: "mesadmin"
      POSTGRES_USER: "estation"
      POSTGRES_PASS: "mesadmin"
      POSTGRES_DBNAME: "estationdb"
      POSTGRES_PORT: "5432"
      DEFAULT_ENCODING: "UTF8"
      DEFAULT_COLLATION: "en_US.UTF-8"
      DEFAULT_CTYPE: "en_US.UTF-8"
      # POSTGRES_MULTIPLE_EXTENSIONS: "postgis,adminpack,postgis_topology"
      POSTGRES_MULTIPLE_EXTENSIONS: "postgis,adminpack"
      POSTGRES_TEMPLATE_EXTENSIONS: "true"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      WAL_SIZE: "4GB"
      MIN_WAL_SIZE: "2048MB"
      WAL_SEGSIZE: "1024"
      MAINTAINANCE_WORK_MEM: "1320MB"
      MAX_CONNECTIONS: "500"
      SHARED_BUFFERS: "1024MB"
      WORK_MEM: "128MB"
    image: "climatestation/postgis:2.0"
    ports:
      - ${CS_PGPORT}:5432
    networks:
      - default
      - jupyterhub
    restart: unless-stopped
    volumes:
      - ${DATA_VOLUME}/static_data/db_dump:/data/static_data/db_dump:rw
      - cs-docker-postgresql12-volume:/var/lib/postgresql:rw
      - ./log/postgres:/var/log/climatestation:rw
      # - ./src:/var/www/climatestation:rw
      # - /var/run/docker.sock:/var/run/docker.sock:rw
      # - ./postgresql:/var/lib/postgresql:rw

networks:
  default:
  jupyterhub:
    external: true

# create an external docker volume: docker volume create --name cs-docker-postgresql12-volume -d local
volumes:
  cs-docker-postgresql12-volume:
    external: true